### ISSUE TITLE
Pre-training VGGx2.caffemodel and VGGx4.caffemodel

### ISSUE THREAD

**Issue by tanhui2975** [yihui-he/py-faster-rcnn#2]
Since we may train our own dataset for detection,could you please provide the pre-training VGGx2.caffemodel and VGGx4.caffemodel in the folder "data/imagenet_models/"?

**Comment by ethanhe42** [comment]
Uploaded just now.
https://github.com/yihui-he/channel-pruning/releases/tag/faster-RCNN-2X4X
